version: '3.2'

services:
  resurface:
    image: resurfaceio/resurface:2.3.1
    container_name: express_resurface
    ports:
      - '4000:4000'
      - '4001:4001'
      - '4002:4002'

  express:
    image: test-express
    container_name: express
    ports:
      - '80:5000'
    env_file:
      - .env
