version: '3.2'

services:
  resurface:
    image: docker.resurface.io/release/pilot
    container_name: express_resurface
    ports:
      - '4000:4000'
      - '4001:4001'
      - '4002:4002'

  express:
    image: test-express:latest
    container_name: express
    command: node index.js
    ports:
      - '80:5000'
    env_file:
      - .env
